### Login
POST http://localhost:3056/api/users/login
Content-Type: application/json

{
  "username": "votu2003",
  "password": "NgocTu3105"
}

### Login User
POST http://localhost:3056/api/users/login
Content-Type: application/json

{
  "username": "staff1",
  "password": "staff123"
}


### Create User (Admin Only)
POST http://localhost:3056/api/users/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGZjNGEwZjYwNDE3ZGZmMDc5N2MwZiIsInJvbGUiOiJhZG1pbiIsInBvc2l0aW9uIjoiR2nDoW0gxJHhu5FjIiwiaWF0IjoxNzUwMjMyOTUxLCJleHAiOjE3NTAyMzY1NTF9.-5706p_IPQAC9oOSoODpxXgHTskFxVNPSBmZtlpCjdo

{
  "username": "staff1",
  "password": "staff123",
  "email": "staff1@example.com",
  "fullName": "Nguyen Van A",
  "gender": "Nam",
  "position": "Nhân viên",
  "phoneNumber": "0901234567",
  "department": "Phòng Dự án",
  "directSupervisor": "684d9d5d086fa3fc8f6b2e9d"
}

### Fetch User Profile (Authenticated User)
GET http://localhost:3056/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTI2ZmEyZDI2ZDE5ZDU2OTUwMzE3NiIsInJvbGUiOiJ1c2VyIiwicG9zaXRpb24iOiJOaMOibiB2acOqbiIsImlhdCI6MTc1MDIzMzA0OSwiZXhwIjoxNzUwMjM2NjQ5fQ.oRMIxBcS8Z1Aq3aWJM_XxfFjP8x-SFR7IfASA6gved8