### Đăng nhập (lấy accessToken và refreshToken)
POST http://localhost:3056/api/auth/login
Content-Type: application/json

{
  "username": "votu2003",
  "password": "NgocTu3105"
}


### Refresh Token
POST http://localhost:3056/api/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGZjNGEwZjYwNDE3ZGZmMDc5N2MwZiIsImlhdCI6MTc1MDM0MTg4MCwiZXhwIjoxNzUwOTQ2NjgwfQ.0IeFMdFOZh2flfP9EcQKuwFIbhXJ3lx5MunSsXIeJ7A"
}

### Đăng xuất
POST http://localhost:3056/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGZjNGEwZjYwNDE3ZGZmMDc5N2MwZiIsInJvbGUiOiJhZG1pbiIsImRlcGFydG1lbnQiOiJQaMOybmcgSMOgbmggY2jDrW5oIiwiaWF0IjoxNzUwMzQxOTQyLCJleHAiOjE3NTAzNDU1NDJ9.Co0Vv0RMeyBGiv815Tb6qWFXmUB5QKe-1p0egCzXtbY

### Lấy thông tin user hiện tại
GET http://localhost:3056/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGZjNGEwZjYwNDE3ZGZmMDc5N2MwZiIsInJvbGUiOiJhZG1pbiIsImRlcGFydG1lbnQiOiJQaMOybmcgSMOgbmggY2jDrW5oIiwiaWF0IjoxNzUwMzQxOTQyLCJleHAiOjE3NTAzNDU1NDJ9.Co0Vv0RMeyBGiv815Tb6qWFXmUB5QKe-1p0egCzXtbY

### Lấy danh sách user
GET http://localhost:3056/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGZjNGEwZjYwNDE3ZGZmMDc5N2MwZiIsInJvbGUiOiJhZG1pbiIsImRlcGFydG1lbnQiOiJQaMOybmcgSMOgbmggY2jDrW5oIiwiaWF0IjoxNzUwMzQxOTQyLCJleHAiOjE3NTAzNDU1NDJ9.Co0Vv0RMeyBGiv815Tb6qWFXmUB5QKe-1p0egCzXtbY

### Tạo user mới
POST http://localhost:3056/api/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGZjNGEwZjYwNDE3ZGZmMDc5N2MwZiIsInJvbGUiOiJhZG1pbiIsImRlcGFydG1lbnQiOiJQaMOybmcgSMOgbmggY2jDrW5oIiwiaWF0IjoxNzUwMzQxOTQyLCJleHAiOjE3NTAzNDU1NDJ9.Co0Vv0RMeyBGiv815Tb6qWFXmUB5QKe-1p0egCzXtbY

{
  "username": "newuser1",
  "password": "password123",
  "email": "newuser1@example.com",
  "fullName": "Nguyen Van A",
  "gender": "Nam",
  "position": "Nhân viên",
  "phoneNumber": "0123456789",
  "department": "Phòng Kỹ thuật",
  "role": "manager",
  "directSupervisor": "684fc4a0f60417dff0797c0f"
}

### Cập nhật user
PUT http://localhost:3056/api/users/684fc4a0f60417dff0797c0f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGZjNGEwZjYwNDE3ZGZmMDc5N2MwZiIsInJvbGUiOiJhZG1pbiIsImRlcGFydG1lbnQiOiJQaMOybmcgSMOgbmggY2jDrW5oIiwiaWF0IjoxNzUwMzQyMDU1LCJleHAiOjE3NTAzNDU2NTV9.UOvZ8rSwhl8kYyJGmPHvUSYR95GyBTy8O5FLX076sd8

{
  "phoneNumber": "0987654321"
}

### Xóa user
DELETE http://localhost:3056/api/users/USER_ID
Authorization: Bearer {{token}}

### Lấy danh sách cấp dưới
GET http://localhost:3056/api/users/subordinates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGZjNGEwZjYwNDE3ZGZmMDc5N2MwZiIsInJvbGUiOiJhZG1pbiIsImRlcGFydG1lbnQiOiJQaMOybmcgSMOgbmggY2jDrW5oIiwiaWF0IjoxNzUwMzQyMDU1LCJleHAiOjE3NTAzNDU2NTV9.UOvZ8rSwhl8kYyJGmPHvUSYR95GyBTy8O5FLX076sd8

### Tạo task mới
POST http://localhost:3056/api/tasks/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Task 1",
  "description": "Mô tả task 1"
}

### Lấy danh sách task
GET http://localhost:3056/api/tasks/list
Authorization: Bearer {{token}}

### Lấy chi tiết task
GET http://localhost:3056/api/tasks/TASK_ID
Authorization: Bearer {{token}}

### Cập nhật task
PUT http://localhost:3056/api/tasks/TASK_ID
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Task đã cập nhật"
}

### Duyệt task
PUT http://localhost:3056/api/tasks/TASK_ID/approve
Authorization: Bearer {{token}}

### Xóa task
DELETE http://localhost:3056/api/tasks/TASK_ID
Authorization: Bearer {{token}} 