version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb_data:/data/db

  app:
    build: .
    container_name: task-management-app
    ports:
      - "3056:3056"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/task_management?authSource=admin
    volumes:
      - ./uploads:/usr/src/app/uploads

volumes:
  mongodb_data: 